#!/usr/bin/env node
/**
 * serve-docs — launch a live Docsify SPA for a project's SSoT docs.
 *
 * Zero npm dependencies of its own; the live-reload web server is
 * `npx docsify-cli serve` (needs Node + network on first run). The SPA
 * renders Markdown, Mermaid fences, full-text search, and turns relative
 * Markdown links into in-app navigation. Docsify watches the real files in
 * place, so the session that launched it can keep editing and the browser
 * updates on save.
 *
 *   node serve.mjs                start (default)
 *   node serve.mjs --stop         stop the running server
 *   node serve.mjs --status       print server status
 *
 * Options (start):
 *   --docs a.md,b.md   explicit doc list (default: discovered from the index)
 *   --root <dir>       force the web root (default: common ancestor of the docs)
 *   --name "Title"     SPA title (default: the repo directory name)
 *   --no-open          don't open the browser
 *
 * Scaffold (index.html, _sidebar.md, .nojekyll) is written into the web root
 * and added to .gitignore; runtime state lives in <repo>/.docs-spa/.
 */
import { readFileSync, writeFileSync, existsSync, statSync, readdirSync, mkdirSync, rmSync, openSync } from 'node:fs';
import { resolve, dirname, basename, join, relative, sep, extname } from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import net from 'node:net';

const SELF = fileURLToPath(import.meta.url);
const REPO = process.cwd();
const STATE_DIR = join(REPO, '.docs-spa');
const STATE_FILE = join(STATE_DIR, 'server.json');

// ---------------------------------------------------------------------------
// Args
// ---------------------------------------------------------------------------
function parseArgs(argv) {
  const o = { open: true };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--stop') o.stop = true;
    else if (a === '--status') o.status = true;
    else if (a === '--no-open') o.open = false;
    else if (a === '--docs') o.docs = argv[++i].split(',').map((s) => resolve(REPO, s.trim()));
    else if (a === '--root') o.root = resolve(REPO, argv[++i]);
    else if (a === '--name') o.name = argv[++i];
  }
  return o;
}

// ---------------------------------------------------------------------------
// Doc discovery
// ---------------------------------------------------------------------------
const uniq = (a) => [...new Set(a)];

function discoverFromIndex() {
  for (const guide of ['AGENTS.md', 'CLAUDE.md']) {
    const p = join(REPO, guide);
    if (!existsSync(p)) continue;
    const text = readFileSync(p, 'utf8');
    const re = /\]\(([^)\s]+\.md)(?:#[^)]*)?\)/g;
    const docs = [];
    let m;
    while ((m = re.exec(text))) {
      if (/^[a-z][a-z0-9+.-]*:/i.test(m[1])) continue;
      const full = resolve(REPO, m[1]);
      if (existsSync(full) && statSync(full).isFile()) docs.push(full);
    }
    if (docs.length) return uniq(docs);
  }
  return null;
}

function walkMd(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name.startsWith('.')) continue;
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...walkMd(full));
    else if (extname(name).toLowerCase() === '.md' && name.toLowerCase() !== 'readme.md') out.push(full);
  }
  return out;
}

function discoverByScan() {
  const base = existsSync(join(REPO, 'docs')) ? join(REPO, 'docs') : REPO;
  return walkMd(base);
}

function commonDir(files) {
  if (files.length === 1) return dirname(files[0]);
  const parts = files.map((f) => dirname(f).split(sep));
  const first = parts[0];
  let i = 0;
  for (; i < first.length; i++) {
    if (!parts.every((p) => p[i] === first[i])) break;
  }
  return first.slice(0, i).join(sep) || sep;
}

// ---------------------------------------------------------------------------
// Scaffold
// ---------------------------------------------------------------------------
function titleOf(file, rel) {
  try {
    const m = readFileSync(file, 'utf8').match(/^#\s+(.+?)\s*$/m);
    if (m) return m[1].trim();
  } catch { /* ignore */ }
  return basename(rel, '.md');
}

function buildSidebar(webRoot, docs) {
  const groups = {};
  for (const d of docs) {
    const rel = relative(webRoot, d).split(sep).join('/');
    const grp = rel.includes('/') ? rel.slice(0, rel.lastIndexOf('/')) : '';
    (groups[grp] ||= []).push({ rel, title: titleOf(d, rel) });
  }
  const lines = ['<!-- generated by architect:serve-docs — do not edit by hand -->', ''];
  for (const grp of Object.keys(groups).sort((a, b) => a.localeCompare(b))) {
    if (grp) lines.push('- **' + grp + '/**');
    for (const it of groups[grp].sort((a, b) => a.title.localeCompare(b.title))) {
      lines.push((grp ? '  - ' : '- ') + '[' + it.title + '](' + it.rel + ')');
    }
  }
  return lines.join('\n') + '\n';
}

const escHtml = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const INDEX_HTML = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="UTF-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '  <title>{{NAME}} — Docs</title>',
  '  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css" />',
  '  <style>',
  '    :root { --theme-color: #3b82f6; }',
  '    .markdown-section { max-width: 56rem; }',
  '    .mermaid { text-align: center; }',
  '  </style>',
  '</head>',
  '<body>',
  '  <div id="app">Loading the docs…</div>',
  '  <script>',
  '    function escMermaid(s) {',
  "      return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');",
  '    }',
  '    window.$docsify = {',
  "      name: '{{NAME}}',",
  '      loadSidebar: true,',
  '      relativePath: true,',
  '      subMaxLevel: 3,',
  '      auto2top: true,',
  "      search: { placeholder: 'Search the docs…', noData: 'No matches.', depth: 4 },",
  '      markdown: {',
  '        renderer: {',
  '          code: function (code, lang) {',
  "            if (lang === 'mermaid') { return '<div class=\"mermaid\">' + escMermaid(code) + '</div>'; }",
  '            return this.origin.code.apply(this, arguments);',
  '          }',
  '        }',
  '      },',
  '      plugins: [',
  '        function (hook) {',
  '          hook.doneEach(function () {',
  "            if (window.mermaid) { try { window.mermaid.run({ querySelector: '.mermaid' }); } catch (e) { console.error(e); } }",
  '          });',
  '        }',
  '      ]',
  '    };',
  '  </script>',
  '  <script src="https://cdn.jsdelivr.net/npm/docsify@4"></script>',
  '  <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/plugins/search.min.js"></script>',
  '  <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/plugins/zoom-image.min.js"></script>',
  '  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>',
  "  <script>window.mermaid && window.mermaid.initialize({ startOnLoad: false, theme: 'default' });</script>",
  '</body>',
  '</html>',
  '',
].join('\n');

const GI_OPEN = '# >>> architect serve-docs (generated, safe to delete) >>>';
const GI_CLOSE = '# <<< architect serve-docs (generated) <<<';

function ensureGitignore(webRoot) {
  const gi = join(REPO, '.gitignore');
  const webRel = relative(REPO, webRoot).split(sep).join('/');
  const prefix = webRel ? webRel + '/' : '';
  const block = [GI_OPEN, '/.docs-spa/', '/' + prefix + 'index.html', '/' + prefix + '_sidebar.md', '/' + prefix + '.nojekyll', GI_CLOSE, ''].join('\n');
  let cur = existsSync(gi) ? readFileSync(gi, 'utf8') : '';
  if (cur.includes(GI_OPEN)) return; // already managed
  if (cur && !cur.endsWith('\n')) cur += '\n';
  writeFileSync(gi, cur + (cur ? '\n' : '') + block);
}

// ---------------------------------------------------------------------------
// Server lifecycle
// ---------------------------------------------------------------------------
function freePort() {
  return new Promise((res, rej) => {
    const s = net.createServer();
    s.on('error', rej);
    s.listen(0, () => {
      const { port } = s.address();
      s.close(() => res(port));
    });
  });
}

function readState() {
  if (!existsSync(STATE_FILE)) return null;
  try { return JSON.parse(readFileSync(STATE_FILE, 'utf8')); } catch { return null; }
}

function killPid(pid) {
  if (!pid) return;
  try { process.kill(-pid); } catch { /* not a group leader */ }
  try { process.kill(pid); } catch { /* already gone */ }
}

function stop({ quiet } = {}) {
  const st = readState();
  if (!st) { if (!quiet) console.log('serve-docs: nothing running.'); return; }
  killPid(st.pid);
  try { rmSync(STATE_FILE); } catch { /* ignore */ }
  if (!quiet) console.log('serve-docs: stopped (pid ' + st.pid + ').');
}

function status() {
  const st = readState();
  if (!st) { console.log('serve-docs: not running.'); return; }
  let alive = false;
  try { process.kill(st.pid, 0); alive = true; } catch { /* dead */ }
  console.log('serve-docs: ' + (alive ? 'running' : 'stale (process gone)'));
  console.log('  url  : ' + st.url);
  console.log('  pid  : ' + st.pid);
  console.log('  root : ' + st.webRoot);
  console.log('  docs : ' + st.docs.length);
}

async function start(opts) {
  let docs = opts.docs || discoverFromIndex() || discoverByScan();
  docs = uniq(docs.filter((d) => existsSync(d)));
  if (!docs.length) {
    console.error('serve-docs: no docs found. Add a doc index to AGENTS.md/CLAUDE.md, a docs/ folder, or pass --docs.');
    process.exit(1);
  }
  const webRoot = opts.root || commonDir(docs);
  const name = opts.name || basename(REPO);

  writeFileSync(join(webRoot, 'index.html'), INDEX_HTML.split('{{NAME}}').join(escHtml(name)));
  writeFileSync(join(webRoot, '_sidebar.md'), buildSidebar(webRoot, docs));
  writeFileSync(join(webRoot, '.nojekyll'), '');
  ensureGitignore(webRoot);
  mkdirSync(STATE_DIR, { recursive: true });

  stop({ quiet: true }); // replace any previous server

  const port = await freePort();
  const logPath = join(STATE_DIR, 'server.log');
  const log = openSync(logPath, 'a');
  const args = ['-y', 'docsify-cli', 'serve', webRoot, '--port', String(port)];
  if (opts.open) args.push('--open');
  const child = spawn('npx', args, { detached: true, stdio: ['ignore', log, log], cwd: REPO });
  child.unref();

  const url = 'http://localhost:' + port;
  writeFileSync(STATE_FILE, JSON.stringify({ pid: child.pid, port, url, webRoot, name, docs, startedAt: new Date().toISOString() }, null, 2));

  console.log('serve-docs: ' + docs.length + ' doc(s) → ' + url);
  console.log('  web root : ' + webRoot);
  console.log('  pid      : ' + child.pid + '   (log: ' + relative(REPO, logPath) + ')');
  console.log('  stop     : node "' + SELF + '" --stop');
  console.log('  note     : first run fetches docsify-cli via npx (needs Node + network).');
}

// ---------------------------------------------------------------------------
const opts = parseArgs(process.argv.slice(2));
if (opts.stop) stop();
else if (opts.status) status();
else start(opts);
